# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0714938c46367dccab4a9749997245c6efb989efc070d477554c3409d96d265d7cc36d399aef5534375f828654cd237806e6b26d605cc73f86843f58923e9fa

test:
  secret_key_base: f6746add3f693e512cf669b82dffb7c95e0972ea2342fa6076acb17704279bdd597ceab533ee22391189c54f4637d4b46f40214a085c49f7a83afef0f5351e02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
